/**
 * CRUD helper functions — extracted from index.ts for SRP.
 * Used by PgAdapter and TransactionalPgAdapter.
 */

import type {
  IncludedRelation,
  ReadonlySqb,
} from '@karkardmitry/kadmium-sql-types';
import {
  renderConflictClause,
  renderValueCell,
  type ParamState,
} from './sql-generator';
import { ResultReshaper } from './result-reshaper';
import { assertSqlIdentifier } from './ddl-validate';
import { maxBatchRows } from './batch';

export type QueryFn = (
  text: string,
  values?: unknown[],
) => Promise<{ rows: unknown[] }>;

/** Keys that are auto-generated by the DB and should never appear in INSERT. */
const RESERVED_KEYS = new Set(['id']);

/**
 * Compute the union of keys across all rows, excluding reserved keys (e.g. `id`).
 * Missing keys in individual rows → undefined → PostgreSQL uses DEFAULT/NULL.
 */
export function unionKeys(rows: Record<string, unknown>[]): string[] {
  const keySet = new Set<string>();
  for (const row of rows) {
    for (const k of Object.keys(row)) {
      if (!RESERVED_KEYS.has(k)) keySet.add(k);
    }
  }
  return [...keySet];
}

export function buildInsertSql(
  collectionName: string,
  data: Record<string, unknown>,
): { text: string; values: unknown[] } {
  assertSqlIdentifier(collectionName, 'collection name');
  const keys = Object.keys(data);
  for (const k of keys) assertSqlIdentifier(k, 'column name');
  const columns = keys.map((k) => `"${k}"`).join(', ');
  const values: unknown[] = [];
  const paramIndex: ParamState = { p: 1 };
  const cells = keys.map((k) => renderValueCell(data[k], values, paramIndex));
  const text =
    `INSERT INTO "${collectionName}" (${columns}) VALUES (${cells.join(', ')}) RETURNING *`
      .trim()
      .replace(/\s+/g, ' ');
  return { text, values };
}

export async function createRow(
  queryFn: QueryFn,
  collectionName: string,
  data: Record<string, unknown>,
): Promise<Record<string, unknown>> {
  const { text, values } = buildInsertSql(collectionName, data);
  const result = await queryFn(text, values);
  return result.rows[0] as Record<string, unknown>;
}

export function buildInsertManySql(
  collectionName: string,
  rows: Record<string, unknown>[],
): { text: string; values: unknown[] } {
  if (rows.length === 0)
    throw new Error('createMany requires at least one row');
  assertSqlIdentifier(collectionName, 'collection name');
  const keys = unionKeys(rows);
  for (const k of keys) assertSqlIdentifier(k, 'column name');
  const columns = keys.map((k) => `"${k}"`).join(', ');
  const values: unknown[] = [];
  const paramIndex: ParamState = { p: 1 };
  const valuePlaceholders = rows.map((row) => {
    const cells = keys.map((k) => renderValueCell(row[k], values, paramIndex));
    return `(${cells.join(', ')})`;
  });
  const text =
    `INSERT INTO "${collectionName}" (${columns}) VALUES ${valuePlaceholders.join(', ')} RETURNING *`
      .trim()
      .replace(/\s+/g, ' ');
  return { text, values };
}

export function buildUpsertManySql(
  collectionName: string,
  rows: Record<string, unknown>[],
  conflictTarget: string[],
  doNothing: boolean,
  setMap: Record<string, unknown> | null = null,
): { text: string; values: unknown[] } {
  if (rows.length === 0)
    throw new Error('createMany requires at least one row');
  assertSqlIdentifier(collectionName, 'collection name');
  const keys = unionKeys(rows);
  for (const k of keys) assertSqlIdentifier(k, 'column name');
  const columns = keys.map((k) => `"${k}"`).join(', ');
  const values: unknown[] = [];
  const paramIndex: ParamState = { p: 1 };
  const valuePlaceholders = rows.map((row) => {
    const cells = keys.map((k) => renderValueCell(row[k], values, paramIndex));
    return `(${cells.join(', ')})`;
  });
  const onConflict = renderConflictClause(
    keys,
    conflictTarget,
    doNothing,
    setMap,
    values,
    paramIndex,
  );
  const text =
    `INSERT INTO "${collectionName}" (${columns}) VALUES ${valuePlaceholders.join(', ')}${onConflict} RETURNING *`
      .trim()
      .replace(/\s+/g, ' ');
  return { text, values };
}

export type ManyRowsSqlBuilder = (
  collectionName: string,
  rows: Record<string, unknown>[],
) => { text: string; values: unknown[] };

export async function createManyRows(
  queryFn: QueryFn,
  collectionName: string,
  rows: Record<string, unknown>[],
  builder: ManyRowsSqlBuilder = buildInsertManySql,
): Promise<Record<string, unknown>[]> {
  if (rows.length === 0) return [];
  const batchSize = maxBatchRows(unionKeys(rows).length);
  const results: Record<string, unknown>[] = [];
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const { text, values } = builder(collectionName, batch);
    const result = await queryFn(text, values);
    results.push(...(result.rows as Record<string, unknown>[]));
  }
  return results;
}

export async function rawQuery<T = unknown>(
  queryFn: QueryFn,
  sql: string,
  params?: unknown[],
): Promise<T[]> {
  const result = await queryFn(sql, params);
  return result.rows as T[];
}

/**
 * Срезает префикс `prop.` с ключей JSON-объектов include-подзапросов,
 * превращая `{"author.id":1,"author.name":"..."}` в `{id:1,name:"..."}`.
 * Рекурсивно обрабатывает вложенные include (по дереву includes).
 */
export function unpackIncludeValue(
  value: unknown,
  inc: IncludedRelation,
  nestedMap: Map<string, IncludedRelation>,
): unknown {
  if (Array.isArray(value))
    return value.map((v) => {
      const childMap = new Map(
        inc.internalSqb.includes.map((n) => [n.propertyName, n]),
      );
      return unpackIncludeValue(v, inc, childMap);
    });
  if (value && typeof value === 'object') {
    const out: Record<string, unknown> = {};
    const prefix = `${inc.propertyName}.`;
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      const clean = k.startsWith(prefix) ? k.slice(prefix.length) : k;
      const nestedInc = nestedMap.get(clean);
      out[clean] = nestedInc ? unpackIncludeValue(v, nestedInc, nestedMap) : v;
    }
    return out;
  }
  return value;
}

export function unpackIncludes(
  rows: Record<string, unknown>[],
  includes: readonly IncludedRelation[],
): Record<string, unknown>[] {
  for (const row of rows) {
    for (const inc of includes) {
      if (row[inc.propertyName] !== undefined) {
        const nestedMap = new Map(
          inc.internalSqb.includes.map((n) => [n.propertyName, n]),
        );
        row[inc.propertyName] = unpackIncludeValue(
          row[inc.propertyName],
          inc,
          nestedMap,
        );
      }
    }
  }
  return rows;
}

export function finalizeRows(
  rows: Record<string, unknown>[],
  sqb: ReadonlySqb,
): Record<string, unknown>[] {
  const unpacked = unpackIncludes(rows, sqb.includes);
  const isMulti =
    sqb.isMulti === true || (sqb.tableContext && sqb.tableContext.size > 1);
  if (
    sqb.operation !== 'select' ||
    !isMulti ||
    !sqb.selects ||
    sqb.selects.length === 0
  ) {
    return unpacked;
  }
  return ResultReshaper.reshape(unpacked, sqb.selects || [], [...sqb.includes]);
}
